version: '3'

services:
  todo-app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src/:/todo-api
    networks:
      - todo-net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: postgres:14.0
    ports:
      - 5432:5432
    networks:
      - todo-net
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U superuser"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  test_database:
    image: postgres:14.0
    ports:
      - 5431:5432
    networks:
      - todo-net
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U superuser"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  todo-net: